//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int IdRoom { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int capacity { get; set; }
        public int enabled { get; set; }
        public string note { get; set; }
        public int smart { get; set; }
        public int floor { get; set; }
        public int BuildingIdBuilding { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
